# Trigger build 2
name: Appcast

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: mikker/appcast-workflow/.github/workflows/appcast.yml@main
    secrets: inherit
    permissions:
      pages: write
      id-token: write
